apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    name: api
spec:
  selector:
    matchLabels:
      name: api
  template:
    metadata:
      labels:
        name: api
    spec:
      containers:
        - name: api
          image: kannon/api
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: db
          resources:
            limits:
              memory: '64Mi'
              cpu: '1'
            requests:
              cpu: '50m'
          ports:
            - containerPort: 50051
              name: 'grpc'
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: ClusterIP
  selector:
    name: api
  ports:
    - port: 50051
      targetPort: grpc
      name: grpc
