apiVersion: apps/v1
kind: Deployment
metadata:
  name: kannon
  labels:
    name: kannon
spec:
  selector:
    matchLabels:
      name: kannon
  template:
    metadata:
      labels:
        name: kannon
    spec:
      containers:
        - name: kannon-cp 
          image: ghcr.io/kannon-email/kannon/kannon
          imagePullPolicy: Always
          args: ['--run-api', '--run-bounce', '--run-dispatcher', '--run-verifier', '--run-sender', '--run-smtp' ,'--config', '/etc/kannon/config.yaml']
          resources:
            limits:
              memory: '64Mi'
              cpu: '1'
            requests:
              cpu: '50m'
          ports:
            - containerPort: 50051
              name: 'grpc'
---
apiVersion: v1
kind: Service
metadata:
  name: kannon
spec:
  type: ClusterIP
  selector:
    name: kannon
  ports:
    - port: 50051
      targetPort: grpc
      name: grpc
