apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer
  labels:
    name: mailer
spec:
  selector:
    matchLabels:
      name: mailer
  template:
    metadata:
      labels:
        name: mailer
    spec:
      containers:
        - name: mailer
          image: gyozatech/smtp-mailer
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: db
          resources:
            limits:
              memory: '64Mi'
              cpu: '1'
            requests:
              cpu: '50m'
          ports:
            - containerPort: 50051
              name: 'grpc'
---
apiVersion: v1
kind: Service
metadata:
  name: mailer
spec:
  type: ClusterIP
  selector:
    name: mailer
  ports:
    - port: 50051
      targetPort: grpc
      name: grpc
