apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender
  labels:
    name: sender
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sender
  template:
    metadata:
      labels:
        name: sender
    spec:
      containers:
        - name: sender
          image: ludusrusso/smtp-sender
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: db
          env:
            - name: SENDER_HOST
              value: mailer.ludusrusso.space
          resources:
            limits:
              memory: '64Mi'
              cpu: '1'
            requests:
              cpu: '50m'
          ports:
            - containerPort: 50051
              name: 'grpc'
