name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        application: ['api', 'sender', 'dispatcher']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Vars
        id: get_vars
        run: |
          echo "::set-output name=ts::$(date +%s)"
          echo "::set-output name=sha::$(git rev-parse --short HEAD)"
          echo "::set-output name=branch::$(git rev-parse --abbrev-ref HEAD)"
      - name: Build API
        uses: ./.github/actions/build-docker
        with:
          docker-target: api
          branch: ${{ steps.get_vars.outputs.branch }}
          sha: ${{ steps.get_vars.outputs.sha }}
          ts: ${{ steps.get_vars.outputs.ts }}
      - name: Build Sender
        uses: ./.github/actions/build-docker
        with:
          docker-target: sender
          branch: ${{ steps.get_vars.outputs.branch }}
          sha: ${{ steps.get_vars.outputs.sha }}
          ts: ${{ steps.get_vars.outputs.ts }}
      - name: Build Dispatcher
        uses: ./.github/actions/build-docker
        with:
          docker-target: dispatcher
          branch: ${{ steps.get_vars.outputs.branch }}
          sha: ${{ steps.get_vars.outputs.sha }}
          ts: ${{ steps.get_vars.outputs.ts }}
